name: davis_client
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  audioplayers: ^6.2.0
  camera: ^0.11.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  path_provider: ^2.1.5
  record: ^5.2.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/start.wav
    - assets/sounds/stop.wav
    - assets/sounds/shutter.wav
    - assets/sounds/loading/loading-1.wav
    - assets/sounds/loading/loading-2.wav
    - assets/sounds/loading/loading-3.wav
    - assets/sounds/loading/loading-4.wav

  fonts:
    - family: HumaneFont
      fonts:
        - asset: assets/fonts/humaneweb.woff2

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash.png

  android_12:
    image: assets/images/splash.png
    icon_background_color: "#000000"

  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
